### ISSUE TITLE
SAN certificate support

### ISSUE THREAD

**Issue by larryboymi** [ocelotconsulting/node-letsencrypt-lambda#10]
This is an issue to track development of multi-domain SAN certificates ... thanks for the [request](https://github.com/ocelotconsulting/node-letsencrypt-lambda/issues/9#issuecomment-281869228) in #9  @phoenix-zhu !

I should probably be able to code that this coming weekend..

**Comment by phoenix-zhu** [comment]
cool, look forward to it. 👍

**Comment by larryboymi** [comment]
@phoenix-zhu I just pushed what I think will allow you to utilize SANs in your certificates... see if it makes sense, and if it works, I'll close this.

Thanks!

**Comment by phoenix-zhu** [comment]
Yeah, it works fine, thanks for the update. @larryboymi 
BTW, there is a tiny issue that if I want to get a cert for a non-secondary level domain like 'a.b.c.com' because the code here(https://github.com/ocelotconsulting/node-letsencrypt-lambda/blob/master/src/aws/route53/getHostedZoneId.js#L8) only cuts the last 2 parts of the domain for zone name.

**Comment by larryboymi** [comment]
Thanks again @phoenix-zhu ... I'm going to separate the issues again for tracking purposes. Glad the fix worked!
