### ISSUE TITLE
Make the code configurable from the environment

### ISSUE THREAD

**Issue by jarro2783** [ocelotconsulting/node-letsencrypt-lambda#15]
Thanks for writing this library, it is exactly what I have been looking for the last few months.

I am uploading my lambda function to AWS using terraform, using https://github.com/joshuaspence/npm-lambda-packer. As such, writing to the custom config file is a bit difficult. I have made a few changes in my own fork, which enable the configuration to be read from environment variables: https://github.com/jarro2783/node-letsencrypt-lambda/tree/config_env.

I would be interested in getting something similar merged into your repository.

The main changes I had to make are that `default.json` had to become `default.js`, and then the default values are environment variables. Of course anyone would still be free to configure that if they want, but this way the repo works _as-is_, as a lambda function.

**Comment by larryboymi** [comment]
Thanks for the feedback! Glad the lib is helpful for you!

I've been meaning to modernize the library a little more, and hopefully I'll get to that soon (config, env, language conventions, tests, etc).

I myself deploy the lambda via cloudformation and [lambci](https://github.com/lambci/lambci) rather than terraform, but I'm happy to support both paths. I'll take a look at your branch and see if there's a good path forward for that.

**Comment by blckct** [comment]
How about an option to load the config file from S3?

**Comment by larryboymi** [comment]
@jarro2783 check out cd64572 which was added for the environment variable support (and ACM import function). @blckct I like it but I think that environment variables have become first class citizens in lambda so I think I favor this approach. If enough people feel strongly I'll consider it tho. Thanks for contributing!

**Comment by jarro2783** [comment]
Thanks very much.
